apps/animals/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from . import views

app_name = "animals"

urlpatterns = [
    path(
        "list/",
        include(
            [
                path("by-function/", views.list_animals, name="list_by_function"),
                path("by-class/", views.AnimalListView.as_view(), name="list_by_class"),
            ]
        ),
    ),
    path(
        "with-owner/",
        include(
            [
                path("owners/", views.AnimalsOwnersListView.as_view(), name="animals_owners_list"),
                path("animals-by-owners/<int:pk>/", views.AnimalsListByOwner.as_view(), name="animals_list_by_owner"),
                path("go-to-my-animals/", views.GoToMyAnimalsView.as_view(), name="go_to_my_animals"),
            ]
        ),
    ),
    path("create/", login_required(views.AnimalCreateView.as_view()), name="create"),
    path("update/<int:pk>/", views.AnimalUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.AnimalDeleteView.as_view(), name="delete"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("first-example/", include("apps.first_example.urls")),
    path("animals/", include("apps.animals.urls")),
    path("sessions-example/", include("apps.sessions_example.urls")),
    path("users/", include("apps.users.urls")),
    path("celery-example/", include("apps.celery_example.urls")),
    path("", include("apps.first_example.urls_root")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/animals/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Kind(models.Model):
    name = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.name

    __repr__ = __str__


class Owner(models.Model):
    name = models.CharField(max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    user = models.OneToOneField(
        User,
        on_delete=models.SET_NULL,
        related_name="owner",
        default=None,
        null=True,
        blank=True,
    )

    session_key = models.CharField(
        max_length=100,
        default=None,
        null=True,
        blank=True,
    )

    def __str__(self) -> str:
        return f"{self.name}"

    __repr__ = __str__


class Animal(models.Model):
    name = models.CharField(max_length=100)
    age = models.PositiveSmallIntegerField(
        blank=True,
        default=0,
    )

    owner = models.ForeignKey(
        Owner,
        on_delete=models.SET_NULL,
        related_name="animals",
        default=None,
        null=True,
        blank=True,
    )

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    is_auto_generated = models.BooleanField(default=False)

    avatar = models.ImageField(
        max_length=255,
        upload_to="animals/animal/avatar/",
        blank=True,
        null=True,
    )

    kind = models.ForeignKey(
        Kind,
        on_delete=models.CASCADE,
        related_name="animals",
        default=None,
        null=False,
        blank=False,
    )

    # state = models.CharField(
    #     choices=(
    #         ('alive', 'Alive'),
    #         ('dead', 'Dead'),
    #     ),
    # )

    def __str__(self) -> str:
        return f"{self.name} - {self.age}"

    __repr__ = __str__

apps/animals/forms.py
from django import forms

from apps.animals.models import Animal


class AnimalByOwnerForm(forms.ModelForm):
    class Meta:
        model = Animal
        fields = (
            "name",
            "age",
            "kind",
            "avatar",
            "owner",
        )
        widgets = {
            "owner": forms.HiddenInput(),
        }

apps/animals/views.py
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db.models import Count
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, TemplateView, FormView, RedirectView
from faker import Faker

from apps.animals.forms import AnimalByOwnerForm
from apps.animals.models import Animal, Owner, Kind


def list_animals(request):
    return render(
        request=request,
        template_name="animals/animal_list.html",
        context={
            "object_list": Animal.objects.all(),
        },
    )


class AnimalListView(ListView):
    model = Animal
    queryset = Animal.objects.all().order_by("-modified_at")


class AnimalCreateView(CreateView):
    model = Animal
    fields = (
        "name",
        "age",
        "kind",
        "avatar",
        "is_auto_generated",
    )
    success_url = reverse_lazy("animals:list_by_class")


@method_decorator(login_required, name="dispatch")
class AnimalUpdateView(UpdateView):
    model = Animal
    fields = (
        "id",
        "name",
        "age",
        "kind",
        "avatar",
        "is_auto_generated",
    )
    success_url = reverse_lazy("animals:list_by_class")


class AnimalDeleteView(LoginRequiredMixin, DeleteView):
    model = Animal
    success_url = reverse_lazy("animals:list_by_class")


class AnimalsOwnersListView(TemplateView):
    template_name = "animals/animals_owners_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        owners = Owner.objects.all().annotate(count_animals=Count("animals"))

        context["object_list"] = owners
        return context


class GoToMyAnimalsView(RedirectView):
    # permanent = False
    # query_string = True
    # pattern_name = "animals:animals_list_by_owner"

    def get_redirect_url(self, *args, **kwargs):
        session = self.request.session
        session_key = session.session_key

        if session_key is None:
            session.save()
            session_key = session.session_key

        user = self.request.user
        if user.is_authenticated:
            owner, _ = Owner.objects.get_or_create(
                user=user,
                defaults={
                    "name": user.username,
                    "session_key": session_key,
                },
            )
            if owner.session_key != session_key:
                owner.session_key = session_key
                owner.save()
        else:
            name = Faker().name()
            owner, _ = Owner.objects.get_or_create(
                session_key=session_key,
                defaults={
                    "name": name,
                },
            )

        owner_id = owner.id
        return reverse_lazy("animals:animals_list_by_owner", kwargs={"pk": owner_id})


class AnimalsListByOwner(FormView):
    template_name = "animals/animal_list_by_owner.html"
    form_class = AnimalByOwnerForm

    def get_initial(self):
        initial = super().get_initial()
        owner_id = self.kwargs.get("pk")

        initial["owner"] = owner_id

        initial["name"] = Faker().name()
        initial["age"] = random.randint(1, 20)

        # TODO Get random kind. If not exists, create it.
        initial["kind"] = random.choice(Kind.objects.all().values_list("pk", flat=True))

        return initial

    def get_success_url(self):
        return reverse_lazy("animals:animals_list_by_owner", kwargs={"pk": self.kwargs.get("pk")})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        owner_id = self.kwargs.get("pk")

        owner = Owner.objects.get(pk=owner_id)

        context["owner"] = owner

        context["object_list"] = owner.animals.all().order_by("-modified_at")
        return context

    def form_valid(self, form):
        if form.instance.owner_id != self.kwargs.get("pk"):
            raise ValidationError("Invalid owner")

        form.save()
        return super().form_valid(form)

apps/templates/animals/animal_confirm_delete.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <p>Are you sure you want to delete "{{ object }}"?</p>

        <button type="submit" class="btn btn-danger">Confirm</button>
    </form>
{% endblock %}

apps/templates/animals/animal_form.html
{% extends '_helpers/_base.html' %}

{% block content %}
    {% include 'animals/animal_form__component.html' %}
{% endblock %}

apps/templates/animals/animal_form__component.html
{% load crispy_forms_tags %}


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

apps/templates/animals/animal_list.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <a href="{% url 'animals:create' %}">
        <button class="btn btn-success">
            Create
        </button>
    </a>

    <ul>
        {% for animal in object_list %}
            <li class="row my-elements-box">
                <div class="col my-element-style">
                    <div class="my-avatar">
                        {% if animal.avatar %}
                            <img src="{{ animal.avatar.url }}" alt="Avatar">
                        {% endif %}
                    </div>

                    <div class="my-element-content">
                        <span>{{ animal.name }}</span>
                        <span> - </span>
                        <span>{{ animal.age }}</span>
                        <span> - </span>

                        {% if animal.kind is not None %}
                            <span>{{ animal.kind }}</span>
                        {% else %}
                            <span>Unknown</span>
                        {% endif %}

                        <span> - </span>
                        <span>{{ animal.modified_at }}</span>
                    </div>

                    <div class="my-element-controls">
                        <a href="{% url 'animals:update' pk=animal.id %}">
                            <button class="btn btn-primary">
                                Edit
                            </button>
                        </a>

                        <a href="{% url 'animals:delete' pk=animal.id %}">
                            <button class="btn btn-danger">
                                Delete
                            </button>
                        </a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

apps/templates/animals/animal_list_by_owner.html
{% extends '_helpers/_base.html' %}

{% block content %}
    {# [owner_info]-[BEGIN] #}
    <h4 class="text-center">
        <span>Animals of </span>
        <span>"{{ owner.name }}"</span>
    </h4>
    {# [owner_info]-[END] #}

    {# [animal_creating_form]-[BEGIN] #}
    <div class="card element-centered" style="width: 18em;">
        <div class="card-body">
            <h5 class="card-title">Add your animal</h5>
            {% include 'animals/animal_form__component.html' %}
        </div>
    </div>
    {# [animal_creating_form]-[END] #}


    {# [animals_list]-[BEGIN] #}
    <ul>
        {% for animal in object_list %}
            <li class="row my-elements-box">
                <div class="col my-element-style">
                    <div class="my-avatar">
                        {% if animal.avatar %}
                            <img src="{{ animal.avatar.url }}" alt="Avatar">
                        {% endif %}
                    </div>

                    <div class="my-element-content">
                        <span>{{ animal.name }}</span>
                        <span> - </span>
                        <span>{{ animal.age }}</span>
                        <span> - </span>

                        {% if animal.kind is not None %}
                            <span>{{ animal.kind }}</span>
                        {% else %}
                            <span>Unknown</span>
                        {% endif %}

                        <span> - </span>
                        <span>{{ animal.modified_at }}</span>
                    </div>

                    <div class="my-element-controls">
                        <a href="{% url 'animals:update' pk=animal.id %}">
                            <button class="btn btn-primary">
                                Edit
                            </button>
                        </a>

                        <a href="{% url 'animals:delete' pk=animal.id %}">
                            <button class="btn btn-danger">
                                Delete
                            </button>
                        </a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
    {# [animals_list]-[END] #}
{% endblock %}

apps/templates/animals/animals_owners_list.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <a href="{% url 'animals:go_to_my_animals' %}">
        <button class="btn btn-success">
            Go to my animals
        </button>
    </a>

    <ul>
        {% for owner_data in object_list %}
            <li class="row my-elements-box">
                <div class="col my-element-style">
                    <div class="my-element-content">
                        <span>
                        {{ owner_data.name }}
                        </span>
                        <span> - </span>
                        <span>
                        {{ owner_data.count_animals }} animals
                        </span>
                    </div>


                    <div class="my-element-controls">
                        <a href="{% url 'animals:animals_list_by_owner' pk=owner_data.id %}">
                            <button class="btn btn-primary">
                                Go to animals
                            </button>
                        </a>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}