apps/animals/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from . import views

app_name = "animals"

urlpatterns = [
    path(
        "list/",
        include(
            [
                path("by-function/", views.list_animals, name="list_by_function"),
                path("by-class/", views.AnimalListView.as_view(), name="list_by_class"),
            ]
        ),
    ),
    path(
        "with-owner/",
        include(
            [
                path("owners/", views.AnimalsOwnersListView.as_view(), name="animals_owners_list"),
                path("animals-by-owners/<int:pk>/", views.AnimalsListByOwner.as_view(), name="animals_list_by_owner"),
                path("go-to-my-animals/", views.GoToMyAnimalsView.as_view(), name="go_to_my_animals"),
            ]
        ),
    ),
    path("create/", login_required(views.AnimalCreateView.as_view()), name="create"),
    path("update/<int:pk>/", views.AnimalUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", views.AnimalDeleteView.as_view(), name="delete"),
]

apps/celery_example/urls.py
from django.urls import path

from . import views

app_name = "celery_example"

urlpatterns = [
    path("", views.CeleryView.as_view(), name="index"),
]

apps/first_example/urls.py
from django.urls import path, include

from . import views

app_name = "first_example"

urlpatterns = [
    path(
        "hello/",
        include(
            [
                # path("", views.greetings, name="index"),
                # path("<str:name>/<int:age>", views.greetings, name="hello_with_args"),
                path("", views.GreetingsView.as_view(), name="index"),
                path("<str:name>/<int:age>/", views.GreetingsView.as_view(), name="hello_with_args"),
            ]
        ),
    ),
    path("humans/", views.HumansView.as_view(), name="humans"),
]

apps/sessions_example/urls.py
from django.urls import path

from . import views

app_name = "sessions_example"

urlpatterns = [
    path("", views.SessionExampleView.as_view(), name="index"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("first-example/", include("apps.first_example.urls")),
    path("animals/", include("apps.animals.urls")),
    path("sessions-example/", include("apps.sessions_example.urls")),
    path("users/", include("apps.users.urls")),
    path("celery-example/", include("apps.celery_example.urls")),
    path("", include("apps.first_example.urls_root")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/_helpers/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if title %}
            {{ title }} |
        {% endif %}
        My Awesome Blog
    </title>

    {# [connect_bootstrap]-[BEGIN] #}
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossorigin="anonymous"
    >
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"
    ></script>
    {# [connect_bootstrap]-[END] #}
    <link
            href="{% static 'styles/index.css' %}"
            rel="stylesheet"
    >
</head>
<body>
<div class="container-fluid">
    {% include '_helpers/_header.html' %}

    {% block content %}
        Hello!
    {% endblock %}
</div>
</body>
</html>

apps/templates/_helpers/_header.html
<header class="header-box">
    <div>
        Logo
    </div>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'root:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'first_example:index' %}">Greetings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'first_example:hello_with_args' name='Mary' age=52 %}">Greetings with
                    args</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'first_example:humans' %}">Humans</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'animals:list_by_class' %}">Animals</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'animals:animals_owners_list' %}">Animals owners</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'sessions_example:index' %}">Sessions</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'celery_example:index' %}">Celery example</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
        </ul>
    </nav>

    <div class="user-box">
        {% if user.is_authenticated %}
            <div class="user-info">
                <p>{{ user.username }}</p>
            </div>

            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login</a>

        {% endif %}
    </div>
</header>